version: '3.8'

services:
  app:
    build: .
    ports:
      - "5005:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/todolist?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - todolist-network

  mysql:
    image: mysql:8.0
    ports:
      - "5006:3306"
    environment:
      - MYSQL_DATABASE=todolist
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - todolist-network

  redis:
    image: redis:6.2
    ports:
      - "5007:6379"
    volumes:
      - redis-data:/data
    networks:
      - todolist-network

networks:
  todolist-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: 