server:
  port: 8080

spring:
  application:
    name: TodoList
    version: 1.0.0
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/todolist?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: jh529529

  data:
    redis:
      host: redis
      port: 6379
      database: 0
  
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
    cache-names:
      - taskCache
      - taskListCache

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true

logging:
  file:
    name: /var/log/todolist/app.log
  level:
    root: INFO
    com.jaehua.todolist: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl 