server:
  port: 8080

spring:
  application:
    name: TodoList
    version: 1.0.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todolist?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: jh529529
  # Flyway配置
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true
    validate-on-migrate: true
  # DevTools配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**
  profiles:
    active: dev  # 默认使用开发环境
  # Redis配置
  cache:
    type: redis
    cache-names:
      - taskCache
      - taskListCache

# MyBatis-Plus通用配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jaehua.todolist.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400

# Swagger通用配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.jaehua.todolist.controller


